_repos: []
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        exclude: infrastructure/terraform/helm/.*/templates
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      -   id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1 
    hooks:
      -   id: flake8
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v5.6.10
    hooks:
      - id: cspell
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: check_main_terraform
        args: [ "markdown", "table", "--output-file", "terraform_docs.md", "--recursive", "--recursive-path", "./infrastructure/terraform", "."]
      - id: terraform-docs-go
        name: check_kafka_terraform
        args: [ "markdown", "table", "--output-file", "terraform_docs.md", "--recursive", "--recursive-path", "./infrastructure/kafka/terraform", "."]
      - id: terraform-docs-go
        name: check_s3_bucket_terraform
        args: [ "markdown", "table", "--output-file", "terraform_docs.md", "--recursive", "--recursive-path", "./infrastructure/terraform/s3_bucket/modules", "."]

